Document: chibi-scheme
Title: Debian chibi-scheme Manual
Author: <insert document author here>
Abstract: This manual describes what chibi-scheme is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/chibi-scheme/chibi-scheme.sgml.gz

Format: postscript
Files: /usr/share/doc/chibi-scheme/chibi-scheme.ps.gz

Format: text
Files: /usr/share/doc/chibi-scheme/chibi-scheme.text.gz

Format: HTML
Index: /usr/share/doc/chibi-scheme/html/index.html
Files: /usr/share/doc/chibi-scheme/html/*.html
